set -g prefix C-q
setw -g mode-keys emacs

set -g mouse on
set -g default-shell "$SHELL"

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g status-position top

# Basalt (b1-b4)
set -g @b1 '#14191f'
set -g @b2 '#1C2228'
set -g @b3 '#20232B'
set -g @b4 '#262A30'

# Sea (s1-s4)
set -g @s1 '#285A6B'
set -g @s2 '#3E7C8F'
set -g @s3 '#5C9FB2'
set -g @s4 '#94dff7'

# Camellia (c1-c4)
set -g @c1 '#A04C62'
set -g @c2 '#B6677C'
set -g @c3 '#CF8899'
set -g @c4 '#f7b5c7'

# Hallabong (h1-h4)
set -g @h1 '#C45A26'
set -g @h2 '#D87237'
set -g @h3 '#E88C4C'
set -g @h4 '#F7A967'

# Moss (m1-m2)
set -g @m1 '#467159'
set -g @m2 '#54846B'

# Lavender (l1-l2)
set -g @l1 '#9F7EB5'
set -g @l2 '#cabbed'

set -g pane-active-border-style "bg=default fg=#{@c4}"

set -g @tbg '#14191f'

set -g status-bg '#14191f'
set -g status-fg '#ffffff'

set -g status-left-length 40
set -g status-left "#[fg=#ffffff,bg=#a04c62]   #S #[fg=default,bg=default]#[fg=#a04c62,bg=#92465b]#[fg=default,bg=default]#[fg=#92465b,bg=#844154]#[fg=default,bg=default]#[fg=#844154,bg=#763c4d]#[fg=default,bg=default]#[fg=#763c4d,bg=#683747]#[fg=default,bg=default]#[fg=#683747,bg=#5a3240]#[fg=default,bg=default]#[fg=#5a3240,bg=#4c2d39]#[fg=default,bg=default]#[fg=#4c2d39,bg=#3e2833]#[fg=default,bg=default]#[fg=#3e2833,bg=#30232c]#[fg=default,bg=default]#[fg=#30232c,bg=#211e25]#[fg=default,bg=default]#[fg=#211e25,bg=#14191f]#[fg=#ffffff,bg=default]   "
set -g status-right "#[fg=#000000, bg=#{@tbg}]#[fg=#ffffff, bg=#000000] %H:%M   #[fg=#000000, bg=#{@tbg}]  "

set -g window-status-format " #[fg=#ffffff,bg=#{@tbg},nobold,noitalics,nounderscore]#W "
set -g window-status-current-format "#[fg=#{@b4},bg=#{@tbg},nobold,noitalics,nounderscore]#[fg=#ffffff,bg=#{@b4}] #W #[fg=#{@b4},bg=#{@tbg},nobold,noitalics,nounderscore]"
set -g window-status-separator "   "

bind -n WheelUpPane if -F "#{alternate_on}" "send-keys -M" "copy-mode -e; send -M"
bind -n WheelDownPane if -F "#{alternate_on}" "send-keys -M" "send -M"
bind -n MouseDragEnd1Pane if -F "#{alternate_on}" "send-keys -M" "send -M"

bind-key a display-popup -E "#{@muljil-plugin-dir}/scripts/sane_tmux.sh"
bind-key A display-popup -E "#{@muljil-plugin-dir}/scripts/add_project.sh"
bind-key R display-popup -E "#{@muljil-plugin-dir}/scripts/rm_project.sh"
bind-key b run-shell "tmux has-session -t main 2>/dev/null || tmux new-session -d -s main; tmux switch-client -t main"

bind-key o select-pane -t :.+
bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R
