alias ls "eza"
alias ll "ls -al"
alias rm "trashutil"
alias zen "flatpak run app.zen_browser.zen"

abbr ga "git add"
abbr gaa "git add -A"
abbr gcm "git commit"
abbr gpu "git push"
abbr nrs "sudo nixos-rebuild switch --flake ~/nixos-dotfiles#airden"
